#!/usr/bin/env node

const dotenv = require('dotenv');
const chokidar = require('chokidar');
const cloudinary = require('cloudinary').v2;
const shelljs = require('shelljs');
const clipboardy = require('clipboardy');

dotenv.config();
cloudinary.config({
  cloud_name: process.env.CLOUD_NAME,
  api_key: process.env.API_KEY,
  api_secret: process.env.API_SECRET
});

chokidar
  .watch('/Users/tyler/Screenshots/', {
    ignored: /(^|[\/\\])\../, // ignores dot files aka .DS_Store
    persistent: true,
    usePolling: true, // performance
    binaryInterval: 5000
  })
  .on('add', path => {
    cloudinary.uploader.upload(path, (e, res) => {
      if (e) console.error(e);
      shelljs.rm(path);
      clipboardy.write(`![altylsyl](${res.secure_url}`);
      console.log(`${path} uploaded to cloudinary`);
    });
  })
  .on('error', error => console.log(`Watcher error: ${error}`));
